services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/
    depends_on:
      - app
      - front

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/
    depends_on:
      - db

  front:
    platform: linux/x86_64
    image: node:20-slim
    working_dir: /app
    command: tail -f /dev/null
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"

  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:5.2.1
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    depends_on:
      - db
    ports:
      - 8080:80

  mailhog:
    platform: linux/x86_64
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
    environment: {}
